services:
  - type: web
    name: mtg-ai-backend
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AIHUBMIX_API_KEY
        sync: false
